spring:
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: true

---
spring:
    profile: local
    datasource:
        testWhileIdle: true
        url: jdbc:mysql://localhost:3306/utility_directory?useSSL=false
        username: jsca
        password: jsca
        validationQuery: SELECT 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
    profiles: test
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:utility_directory;MODE=PostgreSQL
      schema: classpath:/schema.sql
      defaultAutoCommit: false
